### ISSUE TITLE
이메일 알림

### ISSUE THREAD

**Issue by thflthdi** [Dokeey/Buy-Sell#12]
패스워드 변경시에나 특이사항이 있을 때 이메일 알람 기능

**Comment by Dokeey** [comment]
- 패스워드 변경시
- 자신의 물품이 팔렸을시
- 물품에 문의가 달렸을시
- 내 가게에 문의가 달렸을시
- 1:1 문의 답변이 왔을때

**Comment by Dokeey** [comment]
- 1:1 문의 답변에 관한 이메일 알람을 제외하고는 구현완료했습니다. 
- 1:1 문의 답변은 현재 관리자(admin)페이지에서 해당 글을 수정하여 댓글을 작성하는 식으로 구현되어있어 send_mail을 호출하는데에 있어 어려움이 있습니다.
- 추후 1:1 문의 관련 view와 관련하여 수정되거나 관리자 페이지를 리뉴얼할때 추가할 예정입니다.
