### ISSUE TITLE
인기 스토어 메뉴 구현

### ISSUE THREAD

**Issue by Dokeey** [Dokeey/Buy-Sell#47]
## 인기스토어 들어가면 인기상점들이 정렬이 되게 구현.

- 팔로워순
- 조회순
- 댓글많은 순 등등

**Comment by thflthdi** [comment]
가게 조회순, 아이템 판매순, 가게 평점순, 가게 팔로워순 으로 
상위 6위 까지의 가게가 나오도록 구현하였다.
