### ISSUE TITLE
deleteuser 기능 버그

### ISSUE THREAD

**Issue by thflthdi** [Dokeey/Buy-Sell#77]
모든 앱에서 deleteuser 기능이 작동 되고 있지않음

**Comment by Dokeey** [comment]
현재 deleteuser 기능은 migrate 당시 deleteuser.id의 값을 상수로 저장하기 때문에, deleteuser의 id가 변경(삭제 혹은 새로 생성)되면 해당 기능도 작동되지 않게됩니다.
최대한 deleteuser를 변경하지 못하도록 조치하고 변경될 시에는 새로 migrate를 해주는것이 좋습니다.
